steps:
# 1️⃣ Detectar entorno (según BRANCH_NAME) y definir variables de entorno
- name: "gcr.io/cloud-builders/gcloud"
  id: "set-env-vars"
  entrypoint: "bash"
  args:
    - "-c"
    - |
      echo "Detectando entorno a partir de PROJECT_ID=$PROJECT_ID..."
      case "$BRANCH_NAME" in
        *dev*)
          export var_ENV_ACRONYM="dev"
          ;;
        *qa*)
          export var_ENV_ACRONYM="qa"
          ;;
        *prod*)
          export var_ENV_ACRONYM="prod"
          ;;
      esac
      export var_REGION="europe-southwest1"
      env | grep "^var_" > /workspace/env_vars
      echo "Variables detectadas:"
      cat /workspace/env_vars

# 2️⃣ Cargar las variables y desplegar la función
- name: "gcr.io/cloud-builders/gcloud"
  id: "deploy-notifications-engine"
  entrypoint: "bash"
  args:
    - "-c"
    - |
      source /workspace/env_vars &&
      echo "Desplegando NotificationsEngine en entorno $_M_ENV_ACRONYM"
      gcloud functions deploy utilNotificationsWorker \
        --runtime=python312 \
        --gen2 \
        --region=$var_REGION \
        --memory=256MB \
        --entry-point=notificationsWorker \
        --timeout=400s \
        --trigger-topic=notifications \
        --allow-unauthenticated \
        --ingress-settings=internal-only \
        --set-env-vars=_M_PROJECT_ID=$PROJECT_ID,_M_FUNCTION_EXECUTION_REGION=$var_REGION,_M_ENV_ACRONYM=$var_ENV_ACRONYM
  dir: "NotificationsEngine"

options:
  logging: CLOUD_LOGGING_ONLY

timeout: 240s
